services:
  frontend:
    build:
      context: .
      args:
        # PON AQUÍ LA IP DEL DECK + puerto 8000
        VITE_API_URL: "http://192.168.1.109:8000"
    container_name: todo-frontend
    ports:
      - "5173:80"
    restart: unless-stopped