services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend        # <── CAMBIO CLAVE
      dockerfile: Dockerfile
    container_name: todo-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      API_PORT: ${API_PORT}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "8000:8000"

volumes:
  pg_data:
